title: Jiaru Zou's Personal Website
description: Stay gold, Ponyboy, stay gold.
author: Jiaru (Rubin) Zou
avatar: /logo.png
email: jiaruz2@illinois.edu

# baseurl: "Rubin-blog"


plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
linkedin:
  username: ngzhio
  card: summary
logo: logo.png
social:
  name: Jiaru Zou
  links:
    - https://www.linkedin.com/in/jiaru-zou-67434a21a/
    - https://github.com/MP-killer
google_site_verification: u4WXQl0Eu66rsQo2kRdCNx
lang: en
